# Generated by Django 2.0.6 on 2018-06-25 23:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=75)),
                ('course_number', models.CharField(max_length=75)),
                ('prereqs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='DegreePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=75)),
                ('track', models.CharField(max_length=75)),
                ('degree', models.CharField(max_length=75)),
                ('course_name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
                ('major', models.CharField(max_length=75)),
                ('track', models.CharField(max_length=75)),
                ('degree', models.CharField(max_length=75)),
                ('classes_taken', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), size=None)),
            ],
        ),
    ]
