# Generated by Django 2.0.6 on 2018-07-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=75)),
                ('coursenumber', models.CharField(max_length=75)),
                ('semesteravailable', models.CharField(max_length=1)),
                ('numbercredits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrereqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course')),
            ],
        ),
        migrations.CreateModel(
            name='MathCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PossibleDegrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.IntegerField()),
                ('corenumbercredits', models.IntegerField()),
                ('english', models.IntegerField()),
                ('englishnumbercredits', models.IntegerField()),
                ('math', models.IntegerField()),
                ('mathnumbercredits', models.IntegerField()),
                ('speech', models.IntegerField()),
                ('speechnumbercredits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeechCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
                ('degreetrack', models.CharField(max_length=75)),
                ('major', models.CharField(max_length=75)),
                ('classtaken', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('coursenumber', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='corecourse',
            name='coursenumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Course'),
        ),
    ]
