# Generated by Django 2.0.6 on 2018-09-27 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=75)),
                ('course_num', models.CharField(max_length=15)),
                ('course_semester', models.CharField(choices=[('All', 'All'), ('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer', 'Summer')], default='All', max_length=10)),
                ('course_credits', models.IntegerField()),
                ('course_special', models.CharField(choices=[('No', 'No'), ('Lab', 'Lab'), ('Waiver', 'Waiver')], default='No', max_length=15)),
                ('course_comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_diploma', models.CharField(choices=[('Bachelor of Science', 'Bachelor of Science'), ('Master of Science', 'Master of Science'), ('Doctor of Science', 'Doctor of Science')], default='Bachelor of Science', max_length=50)),
                ('degree_type', models.CharField(choices=[('Bachelor of Science', 'Bachelor of Science'), ('Master of Science', 'Master of Science'), ('Doctor of Science', 'Doctor of Science')], default='Major', max_length=50)),
                ('degree_track', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Management Information Systems', 'Management Information Systems'), ('Bioinformatics', 'Bioinformatics'), ('IT Innovation', 'IT Innovation'), ('Cybersecurity', 'Cybersecurity')], default='Computer Science', max_length=50)),
                ('degree_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prereq_type', models.CharField(choices=[('Corequisite', 'Corequisite'), ('Prerequisite', 'Prerequisite')], max_length=20, null=True)),
                ('prereq_courses', models.ManyToManyField(to='landing.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_name', models.CharField(max_length=50)),
                ('req_credits', models.IntegerField()),
                ('req_degrees', models.ManyToManyField(to='landing.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_minCredits', models.IntegerField()),
                ('pref_maxCredits', models.IntegerField()),
                ('pref_summer', models.BooleanField()),
                ('pref_summerMinCredits', models.IntegerField()),
                ('pref_summerMaxCredits', models.IntegerField()),
                ('pref_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Requirement'),
        ),
        migrations.AddField(
            model_name='complete',
            name='complete_courses',
            field=models.ManyToManyField(to='landing.Course'),
        ),
        migrations.AddField(
            model_name='complete',
            name='complete_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
