# Generated by Django 2.0.6 on 2018-10-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='degree_type',
            field=models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor'), ('Concentration', 'Concentration')], default='Major', max_length=50),
        ),
    ]
